### ISSUE TITLE
feat: support signed messages from nano accounts

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-community#105]
**Tasks**
- [x] feat: add api endpoint for signed message (https://github.com/mistakia/nano-community/pull/110)
- [ ] support signed messages from nano accounts updating data pertaining to their account
- [ ] support signed messages directly from account key
- [ ] support linking a signing key
- [ ] support invalidating a signing key

**account data**
  - alias
  - representative metadata
    - cpu
    - ram
    - disk
    - donation address
    - shutdown notice
    - contact information
