### ISSUE TITLE
feat: show voting weight and # of delegators over time on representative page

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-community#108]
**Tasks**

- [ ] rollup voting weight per day
- [ ] rollup # of delegators per day
- [ ] add line chart to representative page

h/t to nano_1111111
