### ISSUE TITLE
feat: enable push notifications for offline representatives

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-community#117]
**Tasks**
- [ ] register for rep notifications
- [ ] unregister for rep notifications
- [ ] create a view to manage rep notifications
