### ISSUE TITLE
setup initial community project management system

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-community#73]
**Tasks**
- [ ] establish starting schema/definitions (properties for each task, acceptable values for each field, etc)

- [ ] get feedback from community (identify any obvious pitfalls, anticipate shortcomings, etc)

- [ ] setup a repo (or dir) for any of the custom functionality of the PM system (associating bounties with tasks/issues)

- [ ] build out the custom functionality and expose it (nano.community, etc). Allow people to interact with the PM system without a github account by simply posting signed messages, eventually fully moving off github.

Starting out, the first set of problems we want to solve:
- have a perpetually up-to-date prioritized list of outstanding community wide tasks
- know who is currently working on what
- know what tasks need to be worked on next that no one is working on
- allow anyone to incentivize the completion of a task via a non-binding voluntarily pledged bounty
