### ISSUE TITLE
chore: migrate missing rows into index tables

### ISSUE THREAD

**Issue by mistakia** [mistakia/nano-community#98]
make sure the following tables are not missing any rows
- [ ] `representatives_uptime_index`
  - [ ] migrate from storage server
  - [x] migrate from production server
- [ ] `representatives_telemetry_index`
  - [ ] migrate from storage server
  - [ ] migrate from production server
- [ ] `representatives_network_index`
  - [ ] migrate from storage server
  - [ ] migrate from production server
- [x] `representatives_meta_index`
  - [x] migrate from storage server
  - [x] migrate from production server
- [ ] `accounts_meta_index`
  - [ ] migrate from storage server
  - [ ] migrate from production server

**Tasks**
- [ ] update the `archive-mysql` to not remove rows from `representatives_telemetry_index` in production server

**Comment by mistakia** [comment]
closed by https://github.com/mistakia/nano-community/commit/61308ab48f1df0d12cdcec5cf4803ebf9efabfda
